export const GET_ONBOARDING_ITEMS_START = 'GET_ONBOARDING_ITEMS_START';
export const GET_ONBOARDING_ITEMS_SUCCESS = 'GET_ONBOARDING_ITEMS_SUCCESS';
export const GET_ONBOARDING_ITEMS_ERROR = 'GET_ONBOARDING_ITEMS_ERROR';

export const GET_CYCLES_START = 'GET_CYCLES_START';
export const GET_CYCLES_SUCCESS = 'GET_CYCLES_SUCCESS';
export const GET_CYCLES_ERROR = 'GET_CYCLES_ERROR';

export const GET_LEVELS_START = 'GET_LEVELS_START';
export const GET_LEVELS_SUCCESS = 'GET_LEVELS_SUCCESS';
export const GET_LEVELS_ERROR = 'GET_LEVELS_ERROR';

export const GET_FAQS_START = 'GET_FAQS_START';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_FAQS_ERROR = 'GET_FAQS_ERROR';

export const GET_POLICY_START = 'GET_POLICY_START';
export const GET_POLICY_SUCCESS = 'GET_POLICY_SUCCESS';
export const GET_POLICY_ERROR = 'GET_POLICY_ERROR';

export const GET_RANKING_START = 'GET_RANKING_START';
export const GET_RANKING_SUCCESS = 'GET_RANKING_SUCCESS';
export const GET_RANKING_ERROR = 'GET_RANKING_ERROR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGOUT = 'LOGOUT';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_QUIZ_START = 'GET_QUIZ_START';
export const GET_QUIZ_SUCCESS = 'GET_QUIZ_SUCCESS';
export const GET_QUIZ_ERROR = 'GET_QUIZ_ERROR';

export const REGISTER_LAST_ANSWER_SUCCESS = 'REGISTER_LAST_ANSWER_SUCCESS';

export const RESET_QUIZ_STATE = 'RESET_QUIZ_STATE';

export const INCREASE_FONT_SIZE = 'INCREASE_FONT_SIZE';
export const DECREASE_FONT_SIZE = 'DECREASE_FONT_SIZE';
export const RESET_FONT_SIZE = 'RESET_FONT_SIZE';
export const SET_FONT = 'SET_FONT';
export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';
export const TOGGLE_COLORS = 'TOGGLE_COLORS';
export const SET_UNDERLINE = 'SET_UNDERLINE';
export const SET_HIGHLIGHT = 'SET_HIGHLIGHT';
export const REMOVE_ANIMATIONS = 'REMOVE_ANIMATIONS';
export const SET_LIGHTS_OFF = 'SET_LIGHTS_OFF';
export const RESET_CONTRAST = 'RESET_CONTRAST';
export const RESET_SETTINGS = 'RESET_SETTINGS';
